fppt/jedis-mock

- src/main/java/com/github/fppt/jedismock/Utils.java
- src/main/java/com/github/fppt/jedismock/operations/OperationFactory.java
- src/main/java/com/github/fppt/jedismock/operations/RO_zadd.java
- src/main/java/com/github/fppt/jedismock/operations/RO_zrange.java
- src/main/java/com/github/fppt/jedismock/operations/RO_zrem.java
- src/test/java/com/github/fppt/jedismock/comparisontests/SimpleOperationsTest.java
The Sorted Set is stored as a LinkedHashMap, with the map's key being the value in the set, and the map's value being the score. This ensures that the values inserted into the set are unique (map's key is unique), and we can easily update the score for a given value. Caveat: every time we insert a new value (or update a value's score), we have to re-sort the LinkedHashMap.
> Adding Basic Sorted Set Operations (zadd, zrem, zrange)

- README.md
- src/main/java/com/github/fppt/jedismock/operations/OperationFactory.java
- src/main/java/com/github/fppt/jedismock/operations/RO_blpop.java
- src/main/java/com/github/fppt/jedismock/operations/RO_bpop.java
- src/main/java/com/github/fppt/jedismock/operations/RO_brpop.java
- src/main/java/com/github/fppt/jedismock/server/SliceParser.java
- src/test/java/com/github/fppt/jedismock/comparisontests/AdvanceOperationsTest.java
adding support for `blpop` and `brpop` base on implementation of `brpoplpush` command
> BLPOP and BRPOP support

- src/main/java/com/github/fppt/jedismock/operations/OperationFactory.java
- src/main/java/com/github/fppt/jedismock/operations/RO_hexists.java
- src/test/java/com/github/fppt/jedismock/comparisontests/SimpleOperationsTest.java
> Add hexists support

- src/main/java/com/github/fppt/jedismock/operations/RO_rpoplpush.java
- src/test/java/com/github/fppt/jedismock/TestCommandParser.java
- src/test/java/com/github/fppt/jedismock/TestRedisServer.java
- src/test/java/com/github/fppt/jedismock/comparisontests/SimpleOperationsTest.java
> Fix rpoplpush when source is empty

- src/main/java/com/github/fppt/jedismock/operations/OperationFactory.java
- src/main/java/com/github/fppt/jedismock/operations/RO_hlen.java
- src/test/java/com/github/fppt/jedismock/comparisontests/SimpleOperationsTest.java
Returns the number of fields contained in the hash stored at the specified key.
Closes #61
> Adding hlen operation.

- src/main/java/com/github/fppt/jedismock/operations/OperationFactory.java
- src/main/java/com/github/fppt/jedismock/operations/RO_hincrby.java
- src/main/java/com/github/fppt/jedismock/operations/RO_hincrbyfloat.java
- src/main/java/com/github/fppt/jedismock/operations/RO_incrOrDecrByFloat.java
- src/main/java/com/github/fppt/jedismock/operations/RO_incrbyfloat.java
- src/main/java/com/github/fppt/jedismock/server/Response.java
- src/test/java/com/github/fppt/jedismock/TestRedisOperationExecutor.java
- src/test/java/com/github/fppt/jedismock/comparisontests/SimpleOperationsTest.java
Add support for incrbyfloat, hincrby and hincrbyfloat operations. Added some test cases for those operations.
>  Add support for incrbyfloat, hincrby and hincrbyfloat operations 

- src/main/java/com/github/fppt/jedismock/storage/ExpiringKeyValueStorage.java
- src/test/java/com/github/fppt/jedismock/comparisontests/SimpleOperationsTest.java
Returns the number of stored keys.
> Consolidate changes

- src/main/java/com/github/fppt/jedismock/operations/OperationFactory.java
- src/main/java/com/github/fppt/jedismock/operations/RO_sismember.java
- src/test/java/com/github/fppt/jedismock/comparisontests/SimpleOperationsTest.java
> Fix #52: implement sismember

- src/main/java/com/github/fppt/jedismock/operations/OperationFactory.java
- src/main/java/com/github/fppt/jedismock/operations/RO_hvals.java
- src/test/java/com/github/fppt/jedismock/comparisontests/SimpleOperationsTest.java
Fix #45: implement `hvals` operation
> Fix #45: implement hvals

- pom.xml
- src/test/java/com/github/fppt/jedismock/TestCommandParser.java
- src/test/java/com/github/fppt/jedismock/TestJedisConnect.java
- src/test/java/com/github/fppt/jedismock/TestRedisOperationExecutor.java
- src/test/java/com/github/fppt/jedismock/TestRedisServer.java
- src/test/java/com/github/fppt/jedismock/TestUtils.java
- src/test/java/com/github/fppt/jedismock/comparisontests/AdvanceOperationsTest.java
- src/test/java/com/github/fppt/jedismock/comparisontests/ComparisonBase.java
- src/test/java/com/github/fppt/jedismock/comparisontests/SimpleOperationsTest.java
Migrate the tests from JUnit4 to JUnit5.
* More modern test framework
* More informative test reports:
> migrate JUnit4 to JUnit5

- src/main/java/com/github/fppt/jedismock/operations/RO_rename.java
- src/test/java/com/github/fppt/jedismock/TestRedisOperationExecutor.java
Hi,
Here is a patch deleting the key before renaming.
/Benoît
> Fix #84 Delete target key before rename

- README.md
- pom.xml
Some minor changes plus testing if the release pipeline still works.
> Release 0.17.0

- src/main/java/com/github/fppt/jedismock/operations/OperationFactory.java
- src/main/java/com/github/fppt/jedismock/operations/RO_client.java
- src/test/java/com/github/fppt/jedismock/TestRedisServer.java
- src/test/java/com/github/fppt/jedismock/comparisontests/SimpleOperationsTest.java
This is a clone of #95 in order to rebase / integrate changes
> Add support for client command

- src/main/java/com/github/fppt/jedismock/operations/OperationFactory.java
- src/main/java/com/github/fppt/jedismock/operations/RO_zremrangebyscore.java
- src/test/java/com/github/fppt/jedismock/comparisontests/TestZRemRangeByScore.java
- src/test/java/com/github/fppt/jedismock/operations/TestZRemRangeByScore.java
Hello Filipe @fppt , 
Hope you are doing great!
Thank you very much for this awesome framework, it's simplified testing and dramatically improved speed for our application!!
One thing to be good to have is `zremrangebyscore` command support(looks like this command will be useful for others as well https://github.com/fppt/jedis-mock/issues/83 )
Could you please have a look at my PR when you have time?
Your feedback is much appreciated!
Thank you very much.
> implement zremrangebyscore

- src/main/java/com/github/fppt/jedismock/operations/RO_hincrbyfloat.java
- src/main/java/com/github/fppt/jedismock/operations/RO_incrOrDecrByFloat.java
- src/main/java/com/github/fppt/jedismock/operations/RO_incrbyfloat.java
- src/test/java/com/github/fppt/jedismock/TestRedisOperationExecutor.java
- src/test/java/com/github/fppt/jedismock/comparisontests/SimpleOperationsTest.java
1. `incrbyfloat` causes exception
2. when incremented by int value, `hincrbyfloat` returns float instead of int
> Fix hincrbyfloat and incrbyfloat

- pom.xml
- src/main/java/com/github/fppt/jedismock/commands/RedisCommand.java
- src/main/java/com/github/fppt/jedismock/datastructures/RMString.java
- src/main/java/com/github/fppt/jedismock/datastructures/RMZSet.java
- src/main/java/com/github/fppt/jedismock/datastructures/Slice.java
- src/main/java/com/github/fppt/jedismock/datastructures/ZSetEntry.java
- src/main/java/com/github/fppt/jedismock/datastructures/ZSetEntryBound.java
- src/main/java/com/github/fppt/jedismock/operations/sortedsets/AbstractByScoreOperation.java
- src/main/java/com/github/fppt/jedismock/operations/sortedsets/ZAdd.java
- src/main/java/com/github/fppt/jedismock/operations/sortedsets/ZRange.java
- src/main/java/com/github/fppt/jedismock/operations/sortedsets/ZRangeByLex.java
- src/main/java/com/github/fppt/jedismock/operations/sortedsets/ZRem.java
- src/main/java/com/github/fppt/jedismock/operations/sortedsets/ZScore.java
- src/main/java/com/github/fppt/jedismock/operations/strings/Append.java
- src/main/java/com/github/fppt/jedismock/operations/strings/IncrOrDecrBy.java
- src/main/java/com/github/fppt/jedismock/operations/strings/IncrOrDecrByFloat.java
- src/main/java/com/github/fppt/jedismock/storage/RedisBase.java
- src/test/java/com/github/fppt/jedismock/commands/RedisCommandTest.java
- src/test/java/com/github/fppt/jedismock/comparisontests/hashes/HashOperationsTest.java
- src/test/java/com/github/fppt/jedismock/comparisontests/sets/SetOperationsTest.java
- src/test/java/com/github/fppt/jedismock/comparisontests/sortedsets/SortedSetOperationsTest.java
- src/test/java/com/github/fppt/jedismock/comparisontests/sortedsets/TestZadd.java
- src/test/java/com/github/fppt/jedismock/comparisontests/strings/TestAppend.java
- src/test/java/com/github/fppt/jedismock/comparisontests/strings/TestSet.java
- src/test/java/com/github/fppt/jedismock/datastructures/RMZSetTest.java
- src/test/java/com/github/fppt/jedismock/datastructures/SliceTest.java
fix https://github.com/fppt/jedis-mock/issues/233
> store string as byte array

- src/main/java/com/github/fppt/jedismock/RedisServer.java
- src/main/java/com/github/fppt/jedismock/server/RedisService.java
fix https://github.com/fppt/jedis-mock/issues/178
> add possibility to set bind address

- src/main/java/com/github/fppt/jedismock/datastructures/RMList.java
- src/main/java/com/github/fppt/jedismock/operations/lists/LPop.java
- src/main/java/com/github/fppt/jedismock/operations/lists/ListPopper.java
- src/main/java/com/github/fppt/jedismock/operations/lists/RPop.java
- src/test/java/com/github/fppt/jedismock/comparisontests/lists/ListOperationsTest.java
Fix #270
* add support for count parameter in LPOP/RPOP
* add unit tests for LPOP with and without count
* refactor code
> Add support for LPOP and RPOP count parameter #270

- src/main/java/com/github/fppt/jedismock/operations/strings/MGet.java
- src/main/java/com/github/fppt/jedismock/operations/strings/MSetNX.java
- src/test/java/com/github/fppt/jedismock/comparisontests/strings/TestMGet.java
- src/test/java/com/github/fppt/jedismock/comparisontests/strings/TestMSetNX.java
> implement msetnx, fix mget

- src/main/java/com/github/fppt/jedismock/operations/sets/SRandMember.java
- src/main/java/com/github/fppt/jedismock/operations/sortedsets/AbstractByScoreOperation.java
- src/main/java/com/github/fppt/jedismock/operations/sortedsets/ZRangeByLex.java
- src/main/java/com/github/fppt/jedismock/server/Response.java
- src/test/java/com/github/fppt/jedismock/comparisontests/sets/SRandMemberTest.java
> fix SRandMember return type

- src/main/java/com/github/fppt/jedismock/datastructures/RMSet.java
- src/main/java/com/github/fppt/jedismock/operations/sets/SPop.java
- src/test/java/com/github/fppt/jedismock/comparisontests/sets/SetOperationsTest.java
> fix spop return type

- src/main/java/com/github/fppt/jedismock/storage/ExpiringKeyValueStorage.java
- src/main/java/com/github/fppt/jedismock/storage/RedisBase.java
- src/test/java/com/github/fppt/jedismock/comparisontests/keys/KeysOperationsTest.java
> fix ConcurrentModificationException when getting & expiring the keys

- README.md
- src/main/java/com/github/fppt/jedismock/operations/cluster/Cluster.java
- src/main/java/com/github/fppt/jedismock/operations/connection/Client.java
- src/main/java/com/github/fppt/jedismock/operations/connection/Echo.java
- src/main/java/com/github/fppt/jedismock/operations/connection/Select.java
- src/main/java/com/github/fppt/jedismock/server/RedisClient.java
- src/main/java/com/github/fppt/jedismock/server/ServiceOptions.java
- src/main/java/com/github/fppt/jedismock/storage/OperationExecutorState.java
- src/test/java/com/github/fppt/jedismock/TestJedisClusterConnect.java
- src/test/java/com/github/fppt/jedismock/TestJedisConnect.java
- src/test/java/com/github/fppt/jedismock/TestLettuceConnection.java
- src/test/java/com/github/fppt/jedismock/comparisontests/cluster/TestCluster.java
- src/test/java/com/github/fppt/jedismock/comparisontests/connection/ConnectionOperationsTest.java
- supported_operations.md
* fix #82 
* fix #133 
* fix #142
> Cluster support

- src/main/java/com/github/fppt/jedismock/operations/strings/GetDel.java
- src/test/java/com/github/fppt/jedismock/comparisontests/strings/TestGetDel.java
Add getDel operation with tests.
fix: #352
> add getdel operation

- README.md
- pom.xml
- src/main/java/com/github/fppt/jedismock/operations/scripting/Eval.java
- src/main/java/com/github/fppt/jedismock/operations/scripting/LuaRedisCallback.java
- src/test/java/com/github/fppt/jedismock/TestRedissonConnection.java
- src/test/java/com/github/fppt/jedismock/comparisontests/scripting/EvalTest.java
> fix lua scripting for Redisson

- src/test/java/com/github/fppt/jedismock/SupportedOperationsGeneratorTest.java
- src/test/java/com/github/fppt/jedismock/comparisontests/ComparisonBase.java
- src/test/java/com/github/fppt/jedismock/comparisontests/sets/SScanTest.java
- src/test/java/com/github/fppt/jedismock/util/OperationCategory.java
- supported_operations.md
Upgrade reference Redis to v. 7.2
> upgrade Redis to v. 7.2

- pom.xml
- src/main/java/com/github/fppt/jedismock/operations/scripting/LuaRedisCallback.java
- src/test/java/com/github/fppt/jedismock/TestRedissonConnection.java
- src/test/java/com/github/fppt/jedismock/comparisontests/scripting/EvalTest.java
> redis.call must return Lua's `false` for null reply

- src/main/java/com/github/fppt/jedismock/operations/hashes/HDel.java
- src/test/java/com/github/fppt/jedismock/comparisontests/hashes/TestHDel.java
> Return error on wrong number of HDEL arguments

- native_tests/linux/tests/unit/type/set.tcl
- src/main/java/com/github/fppt/jedismock/Utils.java
- src/main/java/com/github/fppt/jedismock/operations/sets/SMIsMember.java
- src/main/java/com/github/fppt/jedismock/operations/sets/SPop.java
- src/test/java/com/github/fppt/jedismock/comparisontests/sets/SMIsMemberTest.java
- src/test/java/com/github/fppt/jedismock/comparisontests/sets/SMIsMemberTests.java
- src/test/java/com/github/fppt/jedismock/comparisontests/sets/SetOperationsTest.java
Fix #361 
Also, update native tests for sets
> Implement `smismember`

- src/main/java/com/github/fppt/jedismock/datastructures/streams/StreamId.java
- src/main/java/com/github/fppt/jedismock/operations/cluster/Cluster.java
- src/main/java/com/github/fppt/jedismock/operations/hashes/HGetAll.java
- src/main/java/com/github/fppt/jedismock/operations/hashes/HKeys.java
- src/main/java/com/github/fppt/jedismock/operations/hashes/HMGet.java
- src/main/java/com/github/fppt/jedismock/operations/hashes/HVals.java
- src/main/java/com/github/fppt/jedismock/operations/keys/Keys.java
- src/main/java/com/github/fppt/jedismock/operations/keys/Scan.java
- src/main/java/com/github/fppt/jedismock/operations/lists/BLPop.java
- src/main/java/com/github/fppt/jedismock/operations/lists/BRPop.java
- src/main/java/com/github/fppt/jedismock/operations/server/Time.java
- src/main/java/com/github/fppt/jedismock/operations/sets/SRandMember.java
- src/main/java/com/github/fppt/jedismock/operations/sortedsets/BZPopMax.java
- src/main/java/com/github/fppt/jedismock/operations/sortedsets/BZPopMin.java
- src/main/java/com/github/fppt/jedismock/operations/sortedsets/ZMPop.java
- src/main/java/com/github/fppt/jedismock/operations/sortedsets/ZRevRange.java
- src/main/java/com/github/fppt/jedismock/operations/streams/Ranges.java
- src/main/java/com/github/fppt/jedismock/operations/streams/XRead.java
- src/main/java/com/github/fppt/jedismock/server/Response.java
- src/test/java/com/github/fppt/jedismock/comparisontests/streams/XReadTests.java
> Refactor & fix #452

- src/main/java/com/github/fppt/jedismock/operations/sortedsets/AbstractZRange.java
- src/test/java/com/github/fppt/jedismock/comparisontests/sortedsets/TestZRange.java
> Fix rounding of non-integer scores

- src/main/java/com/github/fppt/jedismock/RedisServer.java
- src/test/java/com/github/fppt/jedismock/TestStartStop.java
> implement isRunning and fix a minor thread leak on RedisServer::stop

- src/main/java/com/github/fppt/jedismock/operations/scripting/Eval.java
- src/test/java/com/github/fppt/jedismock/comparisontests/scripting/EvalTest.java
> introduce an alias for `unpack`

- src/main/java/com/github/fppt/jedismock/operations/streams/XRead.java
- src/test/java/com/github/fppt/jedismock/comparisontests/scripting/EvalTest.java
- src/test/java/com/github/fppt/jedismock/comparisontests/streams/XReadTests.java
> [#540] Fix '$' in XREAD

- src/main/java/com/github/fppt/jedismock/RedisClient.java
- src/main/java/com/github/fppt/jedismock/operations/cluster/Cluster.java
- src/main/java/com/github/fppt/jedismock/storage/OperationExecutorState.java
> Use server, not client host for CLUSTER

- src/main/java/com/github/fppt/jedismock/datastructures/RMBitMap.java
- src/main/java/com/github/fppt/jedismock/datastructures/RMHyperLogLog.java
- src/main/java/com/github/fppt/jedismock/datastructures/StringCompatible.java
- src/main/java/com/github/fppt/jedismock/operations/strings/SetRange.java
- src/test/java/com/github/fppt/jedismock/comparisontests/bitmaps/BitMapsOperationsTest.java
- src/test/java/com/github/fppt/jedismock/comparisontests/strings/TestSetRange.java
> bit set and string compatibility
